name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'
          cache: 'yarn'

      # Build style library
      - name: Install style library dependencies
        working-directory: iptv-style-library
        run: yarn install --frozen-lockfile

      - name: Build style library
        working-directory: iptv-style-library
        run: yarn build

      # Build player (which depends on style library via file:../iptv-style-library)
      - name: Install player dependencies
        working-directory: iptv-player
        run: yarn install --frozen-lockfile

      - name: Build player
        working-directory: iptv-player
        run: yarn build

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'iptv-player/dist'

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
